# https://docs.docker.com/buildx/working-with-buildx/
# TARGETPLATFORM if not empty OR linux/amd64 by default
FROM --platform=${TARGETPLATFORM:-linux/amd64} ghcr.io/roadrunner-server/velox:latest as velox

# app version and build date must be passed during image building (version without any prefix).
# e.g.: `docker build --build-arg "APP_VERSION=1.2.3" --build-arg "BUILD_TIME=$(date +%FT%T%z)" .`
ARG APP_VERSION="undefined"
ARG BUILD_TIME="undefined"

# Copy the configuration file
COPY velox.toml .

# RR doesn't use CGO
ENV CGO_ENABLED=0

# Build the RR binary and put the file into `/usr/bin`
RUN vx build -c velox.toml -o /usr/bin/

# PHP image
FROM --platform=${TARGETPLATFORM:-linux/amd64} php:8.3-cli

# copy required files from builder image
COPY --from=velox /usr/bin/rr /usr/bin/rr

# use the RR binary as image entrypoint
CMD ["/usr/bin/rr"]