name: Linux

on:
  push:
    branches:
      - master
      - pre-release/**
  pull_request:
    branches:
      - master
      - pre-release/**
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "30 5 * * *"

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golang:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7 # action page: <https://github.com/actions/setup-go>
        with:
          go-version-file: go.mod

      - name: Init Go modules Cache # Docs: <https://git.io/JfAKn#go---modules>
        uses: actions/cache@v6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Install Go dependencies
        run: go mod download

      - name: Run golang tests with coverage
        run: make test

  build-sample-rr:
    name: Build sample RoadRunner
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7 # action page: <https://github.com/actions/setup-go>
        with:
          go-version-file: go.mod

      - name: Init Go modules Cache # Docs: <https://git.io/JfAKn#go---modules>
        uses: actions/cache@v6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Install Go dependencies
        run: go mod download

      - name: Build RoadRunner
        env:
          GITHUB_TOKEN: ${{ secrets.RT_TOKEN }}
        run: |
          go install ./cmd/vx
          vx build -c velox.toml -o="."
          ./rr --version
