name: release

on:
  release: # Docs: <https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release>
    types: [published]

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.arch }}, ${{ matrix.compiler }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, darwin] # linux, darwin, windows
        compiler: [gcc] # gcc, musl-gcc
        archiver: [zip] # tar, zip
        arch: [amd64] # amd64, 386
        include:
          - os: linux
            compiler: gcc
            archiver: tar
            arch: amd64
          - os: linux
            compiler: gcc
            archiver: tar
            arch: arm64
          - os: darwin
            compiler: gcc
            archiver: tar
            arch: arm64
          - os: ""
            compiler: musl-gcc # more info: <https://musl.libc.org/>
            archiver: zip
            arch: amd64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Check out code
        uses: actions/checkout@v5

      - name: Install musl
        if: matrix.compiler == 'musl-gcc'
        run: sudo apt-get install -y musl-tools

      - name: Download dependencies
        run: go mod download # `-x` means "verbose" mode

      - name: Generate builder values
        id: values
        run: |
          echo "version=$(echo ${GITHUB_REF##*/} | sed -e 's/^[vV ]*//')" >> $GITHUB_OUTPUT
          echo "timestamp=$(echo $(date +%FT%T%z))" >> $GITHUB_OUTPUT
          echo "binary-name=$(echo $(echo vx`[ ${{ matrix.os }} = 'windows' ] && echo '.exe'`))" >> $GITHUB_OUTPUT

      - name: Compile binary file
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CC: ${{ matrix.compiler }}
          CGO_ENABLED: 0
          LDFLAGS: >-
            -s
            -X github.com/roadrunner-server/velox/v2025/internal/version.version=${{ steps.values.outputs.version }}
            -X github.com/roadrunner-server/velox/v2025/internal/version.buildTime=${{ steps.values.outputs.timestamp }}
        run: |
          go build -trimpath -ldflags "$LDFLAGS" -o "./${{ steps.values.outputs.binary-name }}" ./cmd/vx
          stat "./${{ steps.values.outputs.binary-name }}"

      - name: Generate distributive directory name
        id: dist-dir
        run: >
          echo "name=$(echo velox-${{ steps.values.outputs.version }}-$(
            [ ${{ matrix.os }} != '' ] && echo '${{ matrix.os }}' || echo 'unknown'
          )$(
            [ ${{ matrix.compiler }} = 'musl-gcc' ] && echo '-musl'
          ))-${{ matrix.arch }}" >> $GITHUB_OUTPUT

      - name: Generate distributive archive name
        id: dist-arch
        run: >
          echo "name=$(echo ${{ steps.dist-dir.outputs.name }}.$(
            case ${{ matrix.archiver }} in
              zip) echo 'zip';;
              tar) echo 'tar.gz';;
              *)   exit 10;
            esac
          ))" >> $GITHUB_OUTPUT

      - name: Create distributive
        run: |
          mkdir ${{ steps.dist-dir.outputs.name }}
          mv "./${{ steps.values.outputs.binary-name }}" ./${{ steps.dist-dir.outputs.name }}/
          cp ./README.md ./LICENSE ./velox.toml ./${{ steps.dist-dir.outputs.name }}/

      - name: Pack distributive using tar
        if: matrix.archiver == 'tar'
        run: tar -zcf "${{ steps.dist-arch.outputs.name }}" "${{ steps.dist-dir.outputs.name }}"

      - name: Pack distributive using zip
        if: matrix.archiver == 'zip'
        run: zip -r -q "${{ steps.dist-arch.outputs.name }}" "${{ steps.dist-dir.outputs.name }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ steps.dist-dir.outputs.name }}
          path: ${{ steps.dist-arch.outputs.name }}
          if-no-files-found: error
          retention-days: 30

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.dist-arch.outputs.name }}
          asset_name: ${{ steps.dist-arch.outputs.name }}
          tag: ${{ github.ref }}

  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # Action page: <https://github.com/docker/setup-qemu-action>

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Action page: <https://github.com/docker/setup-buildx-action>

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_LOGIN }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Generate builder values
        id: values
        run: |
          echo "version=$(echo ${GITHUB_REF##*/} | sed -e 's/^[vV ]*//')" >> $GITHUB_OUTPUT
          echo "timestamp=$(echo $(date +%FT%T%z))" >> $GITHUB_OUTPUT

      - name: Build image
        uses: docker/build-push-action@v6 # Action page: <https://github.com/docker/build-push-action>
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            APP_VERSION=${{ steps.values.outputs.version }}
            BUILD_TIME=${{ steps.values.outputs.timestamp }}
          tags: |
            spiralscout/velox:latest
            spiralscout/velox:${{ steps.values.outputs.version }}
            spiralscout/velox:2025
            spiralscout/velox:2025.1

            ghcr.io/roadrunner-server/velox:latest
            ghcr.io/roadrunner-server/velox:${{ steps.values.outputs.version }}
            ghcr.io/roadrunner-server/velox:2025
            ghcr.io/roadrunner-server/velox:2025.1
